#!/usr/bin/env bash
# Grab all the OP_ environment variables and pass them to the Windows environment
# so that 1Password can access them.
# This script is intended to be used as a wrapper for the 1Password CLI in WSL.
# First, it grabs all the OP_ environment variable names without values and suffixes them with /w, as WSL_ENV expects them to be forwarded to win32 calls.
# Then it trims the trailing newline from the list.
# Afterwards, it converts the newline separated to a one-liner colon-separated list.
# Then, it appends this list to the WSLENV environment variable, which is used by WSL to forward environment variables to Windows.

op_env_vars=$(awk 'BEGIN{for(v in ENVIRON) print v"/w"}' | grep OP_ | sed -z '$ s/\n$//' | tr '\n' ':')
export WSLENV="${WSLENV:-}:$(IFS=:; echo "${op_env_vars:-}")"
exec $OP_PATH "$@"